version: '3.3'

services:
  proxy:
    environment:
      VELOCITA_TLS_ENABLED: "true"
    ports:
      - "0.0.0.0:${VELOCITA_HTTPS_PORT}:8443"
    volumes:
      - type: bind
        source: ${VELOCITA_TLS_CERT_FILE}
        target: /etc/nginx/server.crt
        read_only: true
      - type: bind
        source: ${VELOCITA_TLS_KEY_FILE}
        target: /etc/nginx/server.key
        read_only: true
